### ISSUE TITLE
Degrees of freedom calculation when animals in groups

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/mrds#38] opened 2020-11-30 18:57 UTC
Received a question about this from a user in India.  I conducted an investigation with a modified version of the minke data set (ClusterExercise) from old introductory workshop.

Seems degrees of freedom incorrectly calculated when mean group size is used.  Rmarkdown report results attached as PDF.
[degreesfreedombrief.pdf](https://github.com/DistanceDevelopment/Distance/files/5618119/degreesfreedombrief.pdf)

Rmd file plus csv file bundled into a zip file below.
[degfreedom-rmd-csv.zip](https://github.com/DistanceDevelopment/Distance/files/5618140/degfreedom-rmd-csv.zip)

**Comment by dill** [comment] 2021-06-18 09:44
Making some notes here, please feel free to ignore for now...

Taking @erex's data here and reproducing the Distance for Windows analysis (selects hazard key, no adjust):

```
 Effort        :    1842.790
 # samples     :    25
 Width         :    1.500000
 # observations:    88

 Model  1
    Hazard Rate key, k(y) = 1 - Exp(-(y/A(1))**-A(2))


              Point        Standard    Percent Coef.        95% Percent
  Parameter   Estimate       Error      of Variation     Confidence Interval
  ---------  -----------  -----------  --------------  ----------------------
    DS       0.25574E-01  0.66433E-02      25.98      0.15219E-01  0.42975E-01
    E(S)      2.2500      0.22872          10.17       1.8393       2.7524
    D        0.57542E-01  0.16051E-01      27.89      0.33159E-01  0.99853E-01
    N         41161.       11482.          27.89       23719.       71427.
  ---------  -----------  -----------  --------------  ----------------------

 Measurement Units
 ---------------------------------
 Density: Numbers/Sq. kilometers
     ESW: kilometers

 Component Percentages of Var(D)
 -------------------------------
 Detection probability   :  14.8
 Encounter rate          :  71.9
 Cluster size            :  13.3


                         Estimate      %CV     df     95% Confidence Interval
                        ------------------------------------------------------
 Hazard/Cosine          
                 DS     0.25574E-01   25.98    34.49 0.15219E-01  0.42975E-01
                 D      0.57542E-01   27.89    45.44 0.33159E-01  0.99853E-01
                 N       41161.       27.89    45.44  23719.       71427.    
```

(This with "mean of cluster sizes" ticked, R2 ER estimator using n/L.)

Eric reports df=47.37 in his PDF, vs. 45.44 here.


We can fit the same model in `Distance`:

```r
library(Distance)
minke <- read.csv("minkegroups.csv")
minke$Region.Label <- "same"
minke$Area <- 1000000

simple <- ds(minke, key="hr", truncation=1.5)
```

and compare to the output for `Distance::dht2`:

```r
d2 <- dht2(simple, flatfile=minke, strat_formula=~1, innes=FALSE)
```

yielding:

```
> print(d2, "density")
Density estimates from distance sampling
Stratification : geographical 
Variance       : R2, n/L 
Multipliers    : none 
Sample fraction : 1 


Summary statistics:
 .Label  Area CoveredArea  Effort  n  k    ER se.ER cv.ER
  Total 1e+06     5528.37 1842.79 88 25 0.048 0.011 0.237

Density estimates:
 .Label Estimate    se    cv    LCI    UCI     df group_mean group_se
  Total   0.0575 0.016 0.279 0.0332 0.0998 45.436       2.25 0.228718

Component percentages of variance:
 .Label Detection    ER Groups
  Total      14.8 71.92  13.28
```

which matches.

Now for `dht`. Note first that by default `ds` calls `dht` with `varflag=2`, so N/L is used rather than n/L for the encounter rate estimate (see DistanceDevelopment/Distance#95). I've now added an argument to switch this so results below are different from the PDF linked above because of that change *and* inclusion of group size into the degrees of freedom calculation in `mrds`.

Further investigation shows that there are differences in the ER variance, even once the group size component is accounted for. Looking into this now...

**Comment by dill** [comment] 2021-06-18 16:39
Note that for Innes et al, N/L does not require an estimated group size componet. The group size is included in the CV for `varflag=1` (see [here](https://github.com/DistanceDevelopment/mrds/blob/9017b3c134beae9ad2ce73864a0a2700ab403c84/R/dht.se.R#L233)). This is not reflected in the degrees of freedom calculation correctly though (square of sum rather than sum of squares issue).

**Comment by dill** [comment] 2021-06-28 16:28
See commit but this is fixed now I think. For the record...


# no stratification

`dht`:

```r
minke <- read.csv("minkegroups.csv")
minke$Region.Label <- "same"
minke$Area <- 1000000

library(Distance

simple <- ds(minke, key="hr", truncation=1.5, er.method=1, adjustment=NULL)
```

giving:

```
> simple$dht$individuals$D
  Label   Estimate         se        cv        lcl        ucl      df
1 Total 0.05753963 0.01604997 0.2789376 0.03315857 0.09984777 45.4365
> simple$dht$clusters$D
  Label   Estimate          se        cv        lcl        ucl       df
1 Total 0.02557317 0.006642775 0.2597556 0.01521862 0.04297281 34.48699
```

Then using `dht2`:

```r
d2 <- dht2(simple, flatfile=minke, strat_formula=~1, innes=FALSE)
```

Equivalent output to above:

```
> attr(d2, "density")[,c(".Label","Density","Density_CV","LCI","UCI","df")]
  .Label    Density Density_CV        LCI        UCI       df
1  Total 0.05753963  0.2789376 0.03315857 0.09984777 45.43649
> attr(attr(d2, "grouped"), "density")[,c(".Label","Density","Density_CV","LCI",
"UCI","df")]
  .Label    Density Density_CV        LCI        UCI       df
1  Total 0.02557317  0.2597556 0.01521862 0.04297281 34.48699
```

And for Distance for Windows:

```
                         Estimate      %CV     df     95% Confidence Interval
                        ------------------------------------------------------
 Hazard/Cosine          
                 DS     0.25574E-01   25.98    34.49 0.15219E-01  0.42975E-01
                 D      0.57542E-01   27.89    45.44 0.33159E-01  0.99853E-01
                 N       41161.       27.89    45.44  23719.       71427.    
```

# Stratifying by `Region.Label`

Data setup, for export to Distance for Windows later (project attached here [minkestrat.zip](https://github.com/DistanceDevelopment/mrds/files/6725428/minkestrat.zip))

```r
# this is fiddly
minke <- read.csv("minkegroups.csv")
minke2 <- minke
minke2$Region.Label <- NULL
minke2$Area <- NULL
minke2$object <- 1:nrow(minke2)

# re-bind the labels back to the observations
data(minke)
minke <- unique(minke[, c("Sample.Label", "Region.Label", "Area")])
minkes <- merge(minke2, minke, by="Sample.Label", all.x=TRUE)

# order the columns
ord <- c("Study.Area", "Region.Label", "Area", "Sample.Label", "Effort", "distance", "size")
minkes <- minkes[, ord]

# write out for Distance for Windows analysis
write.csv(minkes, file="minkestrat.csv",row.names=FALSE, na="", eol="\n", quote=FALSE)
```

`dht`

```r
library(Distance)
simple2 <- ds(minkes, key="hr", truncation=1.5, er.method=1, adjustment=NULL)
```

```
> simple2$dht$individuals$D
  Label   Estimate         se        cv        lcl        ucl       df
1 North 0.04494292 0.01834346 0.4081501 0.01963416 0.10287512 17.01328
2 South 0.09286326 0.02630640 0.2832811 0.05260341 0.16393584 28.86410
3 Total 0.05061941 0.01677006 0.3312970 0.02580237 0.09930579 19.67767
> simple2$dht$clusters$D
  Label   Estimate          se        cv         lcl        ucl       df
1 North 0.01931757 0.007355987 0.3807926 0.008721974 0.04278487 12.96742
2 South 0.04311508 0.010740360 0.2491091 0.025746327 0.07220099 17.96142
3 Total 0.02213655 0.006758113 0.3052921 0.011726829 0.04178680 15.25427
```

`dht2`

```
d22 <- dht2(simple2, flatfile=minkes, strat_formula=~Region.Label, innes=FALSE)
```

Equivalent output:

```
> attr(d22, "density")[,c("Region.Label","Density","Density_CV","LCI", "UCI","df
")]
  Region.Label    Density Density_CV        LCI        UCI       df
1        North 0.04494292  0.4081501 0.01963416 0.10287512 17.01328
2        South 0.09286326  0.2832810 0.05260341 0.16393584 28.86409
3        Total 0.05061941  0.3296382 0.02586287 0.09907346 19.29727
> attr(attr(d22, "grouped"), "density")[,c("Region.Label","Density","Density_CV"
,"LCI",  "UCI","df")]
  Region.Label    Density Density_CV         LCI        UCI       df
1        North 0.01931757  0.3807926 0.008721974 0.04278487 12.96742
2        South 0.04311508  0.2491091 0.025746327 0.07220099 17.96142
3        Total 0.02213655  0.3052921 0.011726829 0.04178680 15.25427
```

Distance for Windows:

```
                         Estimate      %CV     df     95% Confidence Interval
                        ------------------------------------------------------
 Stratum: North                                             
 Hazard/Cosine          
                 DS     0.19318E-01   38.08    12.97 0.87222E-02  0.42787E-01
                 D      0.44945E-01   40.82    17.01 0.19635E-01  0.10288    
                 N       28341.       40.82    17.01  12381.       64874.    
 Stratum: South                                             
 Hazard/Cosine          
                 DS     0.43117E-01   24.91    17.96 0.25747E-01  0.72205E-01
                 D      0.92867E-01   28.33    28.87 0.52604E-01  0.16394    
                 N       7869.0       28.33    28.87  4457.0       13892.    


 Pooled Estimates:
                         Estimate      %CV     df     95% Confidence Interval
                        ------------------------------------------------------
                 DS     0.22137E-01   30.53    15.26 0.11727E-01  0.41789E-01
                 D      0.50621E-01   33.13    19.64 0.25800E-01  0.99321E-01
                 N       36210.       33.13    19.64  18455.       71046.    
```

Note that we expect some numerical differences due to differences in the finite differencing between `dht` and `dht2`.

**Comment by dill** [comment] 2021-06-28 16:29
This breaks a number of tests in `Distance` so will need to be addressed there. Potentially still some problems for `dht2`, but will address those in the `Distance` repo.

**Closed by dill** 2021-06-28 16:29 UTC
